# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1385d44a4fd34195837f719d96b201a2d8227085ee8e5012becaaadcf1938d65b427b32f3b8a654944aed209c4c68fdeab12fa6f400aba5da3055c6e8b8c89cd

test:
  secret_key_base: 22d3d134215d1affc3cc5bc6f2b68eed47a0875ef282ccc5925a5ffe1edd80f563feb4d191aac064f75c13f0b8f025e4f2ee206b2185f83b9a4c1e9772ca8866

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
